package umc.meme.auth.domain.artist.domain.enums;

public enum Region {
    JONGNO, JUNG, YONGSAN, SEONGDONG, GWANGJIN, DONGDAEMUN,
    JUNGNANG, SEONGBUK, GANGBUK, DOBONG, NOWON, EUNPYEONG,
    SEODAEMUN, MAPO, YANGCHEON, GANGSEO, GURO, GEUMCHEON,
    YEONGDEUNGPO, DONGJAK, GWANAK, SEOCHO, GANGNAM, SONGPA, GANGDONG
}
